# The compiler to use
# CCPREFIX=/home/bioboost/rpi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-
CC=$(CCPREFIX)g++

# Compiler flags
CFLAGS=-c -Wall -std=c++11 -fPIC
    # -c: Compile or assemble the source files, but do not link. The linking stage simply is not done. The ultimate output is in the form of an object file for each source file.
    # -Wall: This enables all the warnings about constructions that some users consider questionable, and that are easy to avoid (or modify to prevent the warning), even in conjunction with macros.

# LDFLAGS=

# Libraries
LIBS=-lc -lpaho-mqttpp3 -lpaho-mqtt3a -lbioslogger

# Name of executable output
NAME=simple_mqtt_client
LIBRARY=lib$(NAME).so
TARGET=$(LIBRARY).1
VERSION=$(LIBRARY).1.0.0
SRCDIR=src
BUILDDIR=bin

OBJS := $(patsubst %.cpp,%.o,$(shell find $(SRCDIR) -name '*.cpp'))

# The .PHONY rule means that examples is not a file that needs to be built
.PHONY: examples

all: makebuildir $(TARGET)

$(TARGET) : $(OBJS)
	$(CC) $(LDFLAGS) -shared -Wl,-soname,$(TARGET) -o $(BUILDDIR)/$(VERSION) $(OBJS) $(LIBS)
# The -fPIC option is needed when linking as it was when compiling to ensure that any code added by the linker is compatible with code previously generated by the compiler.
# The -Wl option passes a comma-separated list of arguments to the linker. As its name suggests, -soname specifies the required soname. If these options are omitted then the library will not have an soname.
# The ldconfig manpage recommends explicitly linking against libc, which has been done above using the -l option (-lc).

%.o : %.cpp
	$(CC) $(CFLAGS) $< -o $@

clean :
	rm -rf $(BUILDDIR)
	rm -f $(OBJS)

makebuildir:
	mkdir -p $(BUILDDIR)

install:
	rm -rf /usr/local/include/$(NAME)
	cp -r include/$(NAME) /usr/local/include
	cp $(BUILDDIR)/$(VERSION) /usr/local/lib
	ln -f -s /usr/local/lib/$(VERSION) /usr/local/lib/$(LIBRARY)
	ln -f -s /usr/local/lib/$(VERSION) /usr/local/lib/$(TARGET)
	ldconfig

examples:
	$(MAKE) -C examples
# The -C flag indicates a change in directory (equivalent to running `cd examples` before calling make).
